version: "3.7"

services:
  ### PHP-FPM ##############################################
  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PHP_VERSION=7.3
        - INSTALL_XDEBUG=TRUE
        - INSTALL_PCOV=TRUE
        - INSTALL_MEMCACHED=FALSE
        - INSTALL_PGSQL=TRUE
        - INSTALL_PG_CLIENT=TRUE
        - USER_ID=1000
        - USER_GROUP=1000
    volumes:
      - .:/var/www
      - ./php-fpm/php7.3.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    networks:
      - backend

  ### NGINX Server #########################################
  nginx:
    build:
      context: ./nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    volumes:
      - .:/var/www
      - ./ngnix/logs:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/ssl/:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
    driver: local
  docker-in-docker:
    driver: local
